# Generated by Django 4.0.3 on 2022-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'WAITING FOR PAYMENT'), ('PAYMENT_RECEIVED', 'PAYMENT RECEIVED'), ('ORDER_SHIPPED', 'ORDER SHIPPED')], default='WAITING_FOR_PAYMENT', max_length=20),
        ),
    ]
